baseURL = 'https://wings-of-tomorrow.org'
languageCode = 'en-us'
title = 'Wings of Tomorrow'
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Welcome to Wings of Tomorrow!"
      introSubtitle = "A platform for aspiring aviators and flight school students to connect with fleet aviators for mentorship and professional development."
      introPhoto = "/logo.jpg"
      logo = "/black_logo_full.png"

    [[languages.en.menu.main]]
        name = "About"
        url = "about"
	weight = 1
		
	[[languages.en.menu.main]]
	name = "Team"
	url = "team"
	weight = 2

	[[languages.en.menu.main]]
	name = "Become a Mentee"
	url = "https://forms.gle/kZbvfH2sSf6EMg9X9"
	weight = 3

	[[languages.en.menu.main]]
	name = "Become a Wingman"
	url = "https://forms.gle/Sz6jnuMYNUMWWCPZ6"
	weight = 4
	
    [[languages.en.menu.main]]
	name = "FAQs"
	url = "faqs"
	weight = 5
	
[params]
  # Enable the darkmode toggle in header
  darkModeToggle = false
  
  # Enable search in header
  enableSearch = false

  # Custom copyright - optional
  ### copyright = "Wings of Tomorrow · All rights reserved"
  ### favicon = "/logo.jpg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Find a Wingman now:"
  description = "Click 'Become a Mentee' above."



[[menu.main]]
  name = "About"
  url = "about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
